version: '3.1'

services:

  redis:
    image: redis:7.2.3-bookworm
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./volumes/redis/:/data
    ports:
      - "6379:6379"

  postgres:
    image: ankane/pgvector:v0.3.1
    environment:
      POSTGRES_DB: db_main
      POSTGRES_USER: db_main
      POSTGRES_PASSWORD: db_main
      PGUSER: db_main
      PGPASSWORD: db_main
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./extra/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/pg/:/var/lib/postgresql/data/
